# Build the app image
FROM python:3.10

# Create directory for the app user
RUN mkdir -p /home/app


# Create the home directory
ENV APP_HOME=/home/app/api
RUN mkdir -p $APP_HOME
WORKDIR $APP_HOME

# install
COPY . $APP_HOME
RUN pip install -r requirements-dev.txt
RUN pip install -e .


CMD ["uvicorn","app.app:app","--host=0.0.0.0","--port=8000","--reload"]